/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Element;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import utils.BdAluno;
import utils.BdEmprestimoAluno;
import utils.BdLivro;
import model.Aluno;
import model.Emprestimo;
import model.Livro;
import model.Professor;
import org.w3c.dom.Attr;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import sun.applet.Main;
import utils.BdEmprestimoProfessor;



/**
 *
 * @author paulojp
 */
public class JFConsultarLivro extends javax.swing.JFrame {  
   
    private JFPrincipal telaPrincipal;
    boolean verifica = false;
    
    /**
     * Creates new form Aluno
     */
    public JFConsultarLivro() {
        initComponents();
        verifica = true;
        // Desabilita os campos ao iniciar a janela
        try { 
            // Após pesquisar os contatos, executa o método p/ exibir o resultado na tabela pesquisa
            listaContatosLivro();
        } catch (SQLException ex) {
            Logger.getLogger(JFConsultarLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        desabilitarCampos();

    }
    
    // Construtor que recebe a instância da tela principal
    JFConsultarLivro(JFPrincipal telaPrincipal) {
        
        this();
        this.telaPrincipal = telaPrincipal;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGPesquisa = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLivro = new javax.swing.JTable();
        jBSair = new javax.swing.JButton();
        jBSair1 = new javax.swing.JButton();
        jBSair3 = new javax.swing.JButton();
        jBSair4 = new javax.swing.JButton();
        jTPesquisar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jBPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jT0Registro = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jT3Disciplina = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jT1Titulo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jT6Cdu = new javax.swing.JTextField();
        jT2Autor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jT7AnoTombamento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jT8Quantidade = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jT9Volume = new javax.swing.JTextField();
        jT10Editora = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jT11AnoPublicado = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jT12LocalPublicado = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jT13FormaAq = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT14Obs = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jT5Cdd = new javax.swing.JTextField();
        jT4Serie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de livros");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar livros"));

        jTableLivro.setAutoCreateRowSorter(true);
        jTableLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTableLivro.setModel(tmLivro);
        jTableLivro.setRowHeight(25);
        jTableLivro.getTableHeader().setReorderingAllowed(false);
        jTableLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLivroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableLivroMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTableLivro);

        jBSair.setBackground(new java.awt.Color(255, 0, 0));
        jBSair.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBSair.setForeground(new java.awt.Color(255, 255, 255));
        jBSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imagens/sair-menu.png"))); // NOI18N
        jBSair.setText("SAIR");
        jBSair.setBorderPainted(false);
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jBSair1.setBackground(new java.awt.Color(0, 153, 0));
        jBSair1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBSair1.setForeground(new java.awt.Color(255, 255, 255));
        jBSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imagens/iconfinder_icon-70-document-file-pdf_315274.png"))); // NOI18N
        jBSair1.setText("PDF DE TODOS OS LIVROS");
        jBSair1.setBorderPainted(false);
        jBSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSair1ActionPerformed(evt);
            }
        });

        jBSair3.setBackground(new java.awt.Color(0, 153, 0));
        jBSair3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBSair3.setForeground(new java.awt.Color(255, 255, 255));
        jBSair3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imagens/iconfinder_search_322497 (1).png"))); // NOI18N
        jBSair3.setText("LIVROS INDISPONÍVEIS");
        jBSair3.setBorderPainted(false);
        jBSair3.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jBSair3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSair3ActionPerformed(evt);
            }
        });

        jBSair4.setBackground(new java.awt.Color(0, 153, 0));
        jBSair4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBSair4.setForeground(new java.awt.Color(255, 255, 255));
        jBSair4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imagens/iconfinder_search_322497 (1).png"))); // NOI18N
        jBSair4.setText("TODOS LIVROS");
        jBSair4.setBorderPainted(false);
        jBSair4.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jBSair4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSair4ActionPerformed(evt);
            }
        });

        jTPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("Título:");

        jBPesquisar.setBackground(new java.awt.Color(0, 153, 0));
        jBPesquisar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imagens/iconfinder_search_322497 (1).png"))); // NOI18N
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Livro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 372));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Registro: ");

        jT0Registro.setBackground(new java.awt.Color(204, 255, 204));
        jT0Registro.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT0Registro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT0Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT0RegistroActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("CDU:");

        jT3Disciplina.setBackground(new java.awt.Color(204, 255, 204));
        jT3Disciplina.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT3Disciplina.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT3Disciplina.setMaximumSize(new java.awt.Dimension(6, 40));
        jT3Disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT3DisciplinaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 1, 10)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("(SE FOR DIDÁTICO)");

        jT1Titulo.setBackground(new java.awt.Color(204, 255, 204));
        jT1Titulo.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT1Titulo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT1Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT1TituloActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Autor:");

        jT6Cdu.setBackground(new java.awt.Color(204, 255, 204));
        jT6Cdu.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT6Cdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT6CduActionPerformed(evt);
            }
        });

        jT2Autor.setBackground(new java.awt.Color(204, 255, 204));
        jT2Autor.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT2Autor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT2Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT2AutorActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Título:");

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Disciplina:");

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Série:");

        jT7AnoTombamento.setBackground(new java.awt.Color(204, 255, 204));
        jT7AnoTombamento.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Ano do tombamento:");

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei", 1, 10)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("(SE FOR DIDÁTICO)");

        jT8Quantidade.setBackground(new java.awt.Color(204, 255, 204));
        jT8Quantidade.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Nº Exemplar:");

        jLabel21.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Volume:");

        jT9Volume.setBackground(new java.awt.Color(204, 255, 204));
        jT9Volume.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N

        jT10Editora.setBackground(new java.awt.Color(204, 255, 204));
        jT10Editora.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT10Editora.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT10Editora.setAlignmentY(0.0F);
        jT10Editora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT10EditoraActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Editora:");

        jT11AnoPublicado.setBackground(new java.awt.Color(204, 255, 204));
        jT11AnoPublicado.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT11AnoPublicado.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT11AnoPublicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT11AnoPublicadoActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Ano publicado:");

        jT12LocalPublicado.setBackground(new java.awt.Color(204, 255, 204));
        jT12LocalPublicado.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Local publicado:");

        jT13FormaAq.setBackground(new java.awt.Color(204, 255, 204));
        jT13FormaAq.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Forma de aquisição:");

        jLabel28.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Observação:");

        jT14Obs.setBackground(new java.awt.Color(204, 255, 204));
        jT14Obs.setColumns(20);
        jT14Obs.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT14Obs.setRows(5);
        jScrollPane3.setViewportView(jT14Obs);

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("CDD:");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 10)); // NOI18N
        jLabel2.setText("(TRÊS PRIMEIROS NÚMEROS)");

        jT5Cdd.setBackground(new java.awt.Color(204, 255, 204));
        jT5Cdd.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT5Cdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT5CddActionPerformed(evt);
            }
        });

        jT4Serie.setBackground(new java.awt.Color(204, 255, 204));
        jT4Serie.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator5)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jT11AnoPublicado, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jT12LocalPublicado, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jT13FormaAq)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19))
                                    .addComponent(jT4Serie))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel2))
                                    .addComponent(jT5Cdd))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT6Cdu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT7AnoTombamento, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT8Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jT9Volume)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT10Editora)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jT0Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jT1Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT2Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12))
                                    .addComponent(jT3Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addComponent(jT0Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jT1Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jT2Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jT3Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22))
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jT9Volume, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jT10Editora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jT8Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(jT4Serie)))
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel17)
                            .addComponent(jLabel2)
                            .addComponent(jLabel18))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT6Cdu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jT7AnoTombamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jT5Cdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT12LocalPublicado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT11AnoPublicado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT13FormaAq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jBPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSair3)
                        .addGap(18, 18, 18)
                        .addComponent(jBSair4))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1297, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBSair1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSair)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBSair4)
                        .addComponent(jBSair3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTPesquisar)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSair1)
                    .addComponent(jBSair))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
     
    
   
   
   
    // TABELA LIVRO - Selecionando registro com o clique do mouse
    private void jTableLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLivroMouseClicked
      // Salva a posição da linha selecionada na tabela de pesquisa       
        int linhaSelecionada = jTableLivro.getSelectedRow();
 
        try {
            BdLivro d = new BdLivro();
            Livro l = new Livro();
            livros = d.select(Integer.valueOf(jTableLivro.getValueAt(linhaSelecionada, 0).toString()));
            
            
            //envia os valores direto do banco de dados para os campos de textos
            jT0Registro.setText(Integer.toString(livros.get(0).getRegistro()));
            jT1Titulo.setText(livros.get(0).getTitulo());
            jT2Autor.setText(livros.get(0).getAutor());
            jT3Disciplina.setText(livros.get(0).getDisciplina());
            if(!(livros.get(0).getSerieDidatica()==0)){
               jT4Serie.setText(Integer.toString(livros.get(0).getSerieDidatica()));
            }
            if(!(livros.get(0).getCdd()==0)){
                String cdd = Integer.toString(livros.get(0).getCdd());
                if(cdd.length()==2){
                    jT5Cdd.setText("0"+(Integer.toString(livros.get(0).getCdd())));
                }else if(cdd.length()==1){
                    jT5Cdd.setText("00"+(Integer.toString(livros.get(0).getCdd())));
                }else{
                    jT5Cdd.setText((Integer.toString(livros.get(0).getCdd())));
                }
            }
            jT6Cdu.setText(livros.get(0).getCdu());
            if(!(livros.get(0).getAnoTombamento()==0)){
            jT7AnoTombamento.setText(Integer.toString(livros.get(0).getAnoTombamento()));
            }
            jT8Quantidade.setText(Integer.toString(livros.get(0).getQuantidade()));
            if(!(livros.get(0).getVolume()==0)){
            jT9Volume.setText(Integer.toString(livros.get(0).getVolume()));
            }
            jT10Editora.setText(livros.get(0).getEditora());
            if(!(livros.get(0).getAnoPublicacao()==0)){
            jT11AnoPublicado.setText(Integer.toString(livros.get(0).getAnoPublicacao()));
            }
            jT12LocalPublicado.setText(livros.get(0).getLocal());
            jT13FormaAq.setText(livros.get(0).getFormaAdquirida());
            jT14Obs.setText(livros.get(0).getObservacao());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar registro.");
        }
       
    }//GEN-LAST:event_jTableLivroMouseClicked

   
   
    // FECHANDO A JANELA
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        // Habilita a tabela principal
        telaPrincipal.setEnabled(true);
        
    }//GEN-LAST:event_formWindowClosed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSair1ActionPerformed
        try {
            try {
                JOptionPane.showMessageDialog(rootPane, "Função indisponível");
                listaContatosLivroImprimir();
            } catch (IOException ex) {
                Logger.getLogger(JFConsultarLivro.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFConsultarLivro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBSair1ActionPerformed

    private void jBSair3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSair3ActionPerformed
        try {
            listaContatosLivroEmprestado();
        } catch (SQLException ex) {
            Logger.getLogger(JFConsultarLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBSair3ActionPerformed

    private void jBSair4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSair4ActionPerformed
        try {
            listaContatosLivro();
        } catch (SQLException ex) {
            Logger.getLogger(JFConsultarLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBSair4ActionPerformed

    private void jTableLivroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLivroMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableLivroMouseEntered

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // Ao clicar em pesquisar, é executado o método que efetua a pesquisa, e outro método que exibe a lista da pesquisa
        try {
            listaContatosLivroPesquisa();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Problemas ao listar registros.");
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jT0RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT0RegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT0RegistroActionPerformed

    private void jT3DisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT3DisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT3DisciplinaActionPerformed

    private void jT1TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT1TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT1TituloActionPerformed

    private void jT6CduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT6CduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT6CduActionPerformed

    private void jT2AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT2AutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT2AutorActionPerformed

    private void jT10EditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT10EditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT10EditoraActionPerformed

    private void jT11AnoPublicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT11AnoPublicadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT11AnoPublicadoActionPerformed

    private void jT5CddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT5CddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT5CddActionPerformed

       
    /* ----LIVRO-> */    
    // Edita os campos e colunas da tabela de resultados
  
    DefaultTableModel tmLivro = new DefaultTableModel(new Object[] {"Registro", "Título", "CDD", "Autor", "Nº Exemplar", "Volume", "Local publicado", "Editora", "Ano publicado", "Disponiblidade" }, 0) {
    @Override
    public boolean isCellEditable(int rowIndex, int mColIndex){  
    return false;  
    }
    };
    List<Livro> livros;
    
    // Lista a quantidade de resultado, de acordo com o nome passado no campo pesquisa
    private void listaContatosLivroEmprestado() throws SQLException {
        BdLivro d = new BdLivro();
        livros = d.getListaEmprestados("%" + "" + "%"); 
        
        // Após pesquisar os contatos, executa o método p/ exibir o resultado na tabela pesquisa
        mostraPesquisaLivroEmprestados(livros);
        livros.clear();
    }
    
    // Lista a quantidade de resultado, de acordo com o nome passado no campo pesquisa
    private void listaContatosLivroPesquisa() throws SQLException {
        BdLivro d = new BdLivro();
        livros = d.getLista("%" + jTPesquisar.getText() + "%"); 
        
        // Após pesquisar os contatos, executa o método p/ exibir o resultado na tabela pesquisa
        mostraPesquisaLivroEmprestados(livros);
        livros.clear();
    }
    
    // Lista a quantidade de resultado, de acordo com o nome passado no campo pesquisa
    private void listaContatosLivro() throws SQLException {
        BdLivro d = new BdLivro();
        livros = d.getLista("%" + "" + "%"); 
        
        // Após pesquisar os contatos, executa o método p/ exibir o resultado na tabela pesquisa
        mostraPesquisaLivroEmprestados(livros);
        livros.clear();
    }
    
    // Lista a quantidade de resultado, de acordo com o nome passado no campo pesquisa
    private void listaContatosLivroImprimir() throws SQLException, IOException {
        BdLivro d = new BdLivro();
        livros = d.getLista("%" + "" + "%"); 
        
        // Após pesquisar os contatos, executa o método p/ exibir o resultado na tabela pesquisa
        imprimirTodosLivros(livros);
        livros.clear();
    }
    
    // Mostra a lista de resultado de acordo com o nome passado no campo pesquisa
    private void mostraPesquisaLivroEmprestados(List<Livro> livros) {
        // Limpa a tabela sempre que for solicitado uma nova pesquisa
        limpaTabelaLivro();
        
        if (livros.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nenhum livro encontrado.");
        } else {            
            // Linha em branco usada no for, para cada registro é criada uma nova linha 
            String[] linha = new String[] {null, null, null, null};
            // P/ cada registro é criada uma nova linha, cada linha recebe os campos do registro
            for (int i = 0; i < livros.size(); i++) {
                tmLivro.addRow(linha);
                tmLivro.setValueAt(livros.get(i).getRegistro(), i, 0);
                tmLivro.setValueAt(livros.get(i).getTitulo(), i, 1);
                if(!(livros.get(i).getCdd()==0)){
                    String cdd = Integer.toString(livros.get(i).getCdd());
                    if(cdd.length()==2){
                        tmLivro.setValueAt("0"+(livros.get(i).getCdd()), i, 2);
                    }else if(cdd.length()==1){
                        tmLivro.setValueAt("00"+(livros.get(i).getCdd()), i, 2);
                    }else{
                        tmLivro.setValueAt(livros.get(i).getCdd(), i, 2);
                    }
                }
                tmLivro.setValueAt(livros.get(i).getAutor(), i, 3);
                tmLivro.setValueAt(livros.get(i).getQuantidade(), i, 4);
                tmLivro.setValueAt(livros.get(i).getVolume(), i, 5);
                tmLivro.setValueAt(livros.get(i).getLocal(), i, 6);
                tmLivro.setValueAt(livros.get(i).getEditora(), i, 7);
                tmLivro.setValueAt(livros.get(i).getAnoPublicacao(), i, 8);
                System.out.println(livros.get(i).getDisponibilidade());
                if((livros.get(i).getDisponibilidade())==false){
                    tmLivro.setValueAt("Indisponível", i, 9);    
                }else{               
                    tmLivro.setValueAt("Disponível", i, 9);
                }    
            }            
        }
    }
    
    //pega a lista de todos os livros cadastrados no banco de dados
    public void imprimirTodosLivros(List<Livro> livros) throws IOException{
        
        if(livros.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Não existem livros cadastrados");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Funcionalidade em Desenvolvimento!");
        } 
    }
    
    // Limpa a tabela de resultados
    private void limpaTabelaLivro() {       
        while (tmLivro.getRowCount() > 0) {            
            tmLivro.removeRow(0);
        }
    }
    /* <-LIVRO---- */  
        
    /* <-PESQUISA---- */         
    
    public void desabilitarCampos(){
        jT0Registro.setEditable(false);
        jT1Titulo.setEditable(false);
        jT2Autor.setEditable(false);
        jT3Disciplina.setEditable(false);
        jT4Serie.setEditable(false);
        jT5Cdd.setEditable(false);
        jT6Cdu.setEditable(false);
        jT7AnoTombamento.setEditable(false);
        jT8Quantidade.setEditable(false);
        jT9Volume.setEditable(false);
        jT10Editora.setEditable(false);
        jT11AnoPublicado.setEditable(false);
        jT12LocalPublicado.setEditable(false);
        jT13FormaAq.setEditable(false);
        jT14Obs.setEditable(false);
    } 
  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFConsultarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFConsultarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFConsultarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFConsultarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFConsultarLivro().setVisible(true);
            }
        });
    }    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGPesquisa;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSair1;
    private javax.swing.JButton jBSair3;
    private javax.swing.JButton jBSair4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jT0Registro;
    private javax.swing.JTextField jT10Editora;
    private javax.swing.JTextField jT11AnoPublicado;
    private javax.swing.JTextField jT12LocalPublicado;
    private javax.swing.JTextField jT13FormaAq;
    private javax.swing.JTextArea jT14Obs;
    private javax.swing.JTextField jT1Titulo;
    private javax.swing.JTextField jT2Autor;
    private javax.swing.JTextField jT3Disciplina;
    private javax.swing.JTextField jT4Serie;
    private javax.swing.JTextField jT5Cdd;
    private javax.swing.JTextField jT6Cdu;
    private javax.swing.JTextField jT7AnoTombamento;
    private javax.swing.JTextField jT8Quantidade;
    private javax.swing.JTextField jT9Volume;
    private javax.swing.JTextField jTPesquisar;
    private javax.swing.JTable jTableLivro;
    // End of variables declaration//GEN-END:variables

}
