/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import model.FormatLetras;
import model.FormatNumbers;
import model.Livro;
import utils.BdLivro;


/**
 *
 * @author paulojp
 */
public class JFLivro extends javax.swing.JFrame {  
    
   
    // Variável que recebe a instância da tela principal
    private JFPrincipal telaPrincipal;
    
    /**
     * Creates new form Aluno
     */
    public JFLivro() {
        initComponents();
        
        // Desabilita os campos ao iniciar a janela
        desabilitaCampos();
        
        //Formata os campos de textos
        jT0Registro.setDocument(new FormatNumbers(5));
        jT1Titulo.setDocument(new FormatLetras(200));
        jT2Autor.setDocument(new FormatLetras(100));
        jT3Disciplina.setDocument(new FormatLetras(100));
        jT4Serie.setDocument(new FormatNumbers(1));
        jT5Cdd.setDocument(new FormatNumbers(3));
        jT6Cdu.setDocument(new FormatLetras(15));
        jT7AnoTombamento.setDocument(new FormatNumbers(4));
        jT8Quantidade.setDocument(new FormatNumbers(3));
        jT9Volume.setDocument(new FormatNumbers(2));
        jT10Editora.setDocument(new FormatLetras(50));
        jT11AnoPublicado.setDocument(new FormatNumbers(4));
        jT12LocalPublicado.setDocument(new FormatLetras(50));
        jT13FormaAq.setDocument(new FormatLetras(200));
        jT14Obs.setDocument(new FormatLetras(200));
    }
    
    
    // Construtor reabilita tela principal - recebe a instância
    JFLivro(JFPrincipal telaPrincipal) throws SQLException {
        
        // this(esta janela 'jFCliente') - abre a própria janela ao execultar o contrutor
        this();
        this.telaPrincipal = telaPrincipal;
        
        BdLivro d = new BdLivro();
        livros = d.getLista("%"+""+"%"); 
        // Após pesquisar os contatos, executa o método p/ exibir o resultado na tabela pesquisa
        mostraPesquisa(livros);
        livros.clear();
     
        // Após pesquisar os contatos, executa o método p/ exibir o resultado na tabela pesquisa     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jT0Registro = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jT3Disciplina = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jT1Titulo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jT6Cdu = new javax.swing.JTextField();
        jT2Autor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jT7AnoTombamento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jT8Quantidade = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jT9Volume = new javax.swing.JTextField();
        jT10Editora = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jT11AnoPublicado = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jT12LocalPublicado = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jT13FormaAq = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT14Obs = new javax.swing.JTextArea();
        jBSair = new javax.swing.JButton();
        jBCadastrar = new javax.swing.JButton();
        jBNovo = new javax.swing.JButton();
        jBCadastrar1 = new javax.swing.JButton();
        jBCadastrar2 = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jT5Cdd = new javax.swing.JTextField();
        jT4Serie = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTPesquisar = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar livros");
        setBackground(new java.awt.Color(0, 184, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Livro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 372));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Registro: ");

        jT0Registro.setBackground(new java.awt.Color(204, 255, 204));
        jT0Registro.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT0Registro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT0Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT0RegistroActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("CDU:");

        jT3Disciplina.setBackground(new java.awt.Color(204, 255, 204));
        jT3Disciplina.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT3Disciplina.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT3Disciplina.setMaximumSize(new java.awt.Dimension(6, 40));
        jT3Disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT3DisciplinaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 1, 10)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("(SE FOR DIDÁTICO)");

        jT1Titulo.setBackground(new java.awt.Color(204, 255, 204));
        jT1Titulo.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT1Titulo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT1Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT1TituloActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("*Autor:");

        jT6Cdu.setBackground(new java.awt.Color(204, 255, 204));
        jT6Cdu.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT6Cdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT6CduActionPerformed(evt);
            }
        });

        jT2Autor.setBackground(new java.awt.Color(204, 255, 204));
        jT2Autor.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT2Autor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT2Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT2AutorActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("*Título:");

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Disciplina:");

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Série:");

        jT7AnoTombamento.setBackground(new java.awt.Color(204, 255, 204));
        jT7AnoTombamento.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Ano do tombamento:");

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei", 1, 10)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("(SE FOR DIDÁTICO)");

        jT8Quantidade.setBackground(new java.awt.Color(204, 255, 204));
        jT8Quantidade.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("*Nº Exemplar:");

        jLabel21.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Volume:");

        jT9Volume.setBackground(new java.awt.Color(204, 255, 204));
        jT9Volume.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N

        jT10Editora.setBackground(new java.awt.Color(204, 255, 204));
        jT10Editora.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT10Editora.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT10Editora.setAlignmentY(0.0F);
        jT10Editora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT10EditoraActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("*Editora:");

        jT11AnoPublicado.setBackground(new java.awt.Color(204, 255, 204));
        jT11AnoPublicado.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT11AnoPublicado.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jT11AnoPublicado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT11AnoPublicadoActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Ano publicado:");

        jT12LocalPublicado.setBackground(new java.awt.Color(204, 255, 204));
        jT12LocalPublicado.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("*Local publicado:");

        jT13FormaAq.setBackground(new java.awt.Color(204, 255, 204));
        jT13FormaAq.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Forma de aquisição:");

        jLabel28.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Observação:");

        jT14Obs.setBackground(new java.awt.Color(204, 255, 204));
        jT14Obs.setColumns(20);
        jT14Obs.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT14Obs.setRows(5);
        jScrollPane2.setViewportView(jT14Obs);

        jBSair.setBackground(new java.awt.Color(255, 0, 0));
        jBSair.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBSair.setForeground(new java.awt.Color(255, 255, 255));
        jBSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imagens/sair-menu.png"))); // NOI18N
        jBSair.setText("SAIR");
        jBSair.setBorderPainted(false);
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jBCadastrar.setBackground(new java.awt.Color(0, 153, 0));
        jBCadastrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jBCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imagens/piece-of-paper-and-pencil_1.png"))); // NOI18N
        jBCadastrar.setText("LIMPAR");
        jBCadastrar.setBorderPainted(false);
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBNovo.setBackground(new java.awt.Color(0, 153, 0));
        jBNovo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBNovo.setForeground(new java.awt.Color(255, 255, 255));
        jBNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imagens/unlock.png"))); // NOI18N
        jBNovo.setText("DESBLOQUEAR");
        jBNovo.setBorderPainted(false);
        jBNovo.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });

        jBCadastrar1.setBackground(new java.awt.Color(0, 153, 0));
        jBCadastrar1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBCadastrar1.setForeground(new java.awt.Color(255, 255, 255));
        jBCadastrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imagens/file.png"))); // NOI18N
        jBCadastrar1.setText("CADASTRAR");
        jBCadastrar1.setBorderPainted(false);
        jBCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrar1ActionPerformed(evt);
            }
        });

        jBCadastrar2.setBackground(new java.awt.Color(0, 153, 0));
        jBCadastrar2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBCadastrar2.setForeground(new java.awt.Color(255, 255, 255));
        jBCadastrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imagens/save-file-option.png"))); // NOI18N
        jBCadastrar2.setText("SALVAR ALTERAÇÕES");
        jBCadastrar2.setBorderPainted(false);
        jBCadastrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrar2ActionPerformed(evt);
            }
        });

        jBExcluir.setBackground(new java.awt.Color(0, 153, 0));
        jBExcluir.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imagens/delete.png"))); // NOI18N
        jBExcluir.setText("EXCLUIR");
        jBExcluir.setBorderPainted(false);
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("apenas números");

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("CDD:");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 10)); // NOI18N
        jLabel2.setText("(TRÊS PRIMEIROS NÚMEROS)");

        jT5Cdd.setBackground(new java.awt.Color(204, 255, 204));
        jT5Cdd.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jT5Cdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT5CddActionPerformed(evt);
            }
        });

        jT4Serie.setBackground(new java.awt.Color(204, 255, 204));
        jT4Serie.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jT11AnoPublicado, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jT12LocalPublicado, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jT13FormaAq)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19))
                                    .addComponent(jT4Serie))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel2))
                                    .addComponent(jT5Cdd))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT6Cdu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT7AnoTombamento, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT8Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jT9Volume)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT10Editora)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel1))
                                    .addComponent(jT0Registro))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jT1Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT2Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addComponent(jT3Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jBCadastrar1)
                        .addGap(18, 18, 18)
                        .addComponent(jBCadastrar2)
                        .addGap(18, 18, 18)
                        .addComponent(jBExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSair)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31))
                    .addComponent(jT0Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jT1Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jT2Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jT3Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22))
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jT9Volume, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jT10Editora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jT8Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(jT4Serie)))
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel2)
                            .addComponent(jLabel18))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT6Cdu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jT7AnoTombamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jT5Cdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT12LocalPublicado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT11AnoPublicado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT13FormaAq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCadastrar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBNovo)
                        .addComponent(jBCadastrar)
                        .addComponent(jBSair)
                        .addComponent(jBCadastrar2)
                        .addComponent(jBExcluir)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar livro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jTPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jBPesquisar.setBackground(new java.awt.Color(0, 153, 0));
        jBPesquisar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imagens/iconfinder_search_322497 (1).png"))); // NOI18N
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jTablePesquisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTablePesquisa.setModel(tmLivro);
        jTablePesquisa.setToolTipText("");
        jTablePesquisa.setRowHeight(25);
        jTablePesquisa.getTableHeader().setReorderingAllowed(false);
        jTablePesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePesquisa);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setText("Título:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jBPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTPesquisar)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jBPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Cadastro de Clientes");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
     
    
    // BOTÃO PESQUISAR - Precionando
    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // Ao clicar em pesquisar, é executado o método que efetua a pesquisa, e outro método que exibe a lista da pesquisa
        try {            
            listaContatos(); 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Problemas ao listar registros.");            
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed
    
    // TABELA PESQUISA - Selecionando registro com o clique do mouse
    private void jTablePesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaMouseClicked
        // Salva a posição da linha selecionada na tabela de pesquisa       
        int linhaSelecionada = jTablePesquisa.getSelectedRow();
 
        try {
            BdLivro d = new BdLivro();
            Livro l = new Livro();
            livros = d.select(Integer.valueOf(jTablePesquisa.getValueAt(linhaSelecionada, 0).toString()));
            
            
            //envia os valores direto do banco de dados para os campos de textos
            jT0Registro.setText(Integer.toString(livros.get(0).getRegistro()));
            jT1Titulo.setText(livros.get(0).getTitulo());
            jT2Autor.setText(livros.get(0).getAutor());
            jT3Disciplina.setText(livros.get(0).getDisciplina());
            if(!(livros.get(0).getSerieDidatica()==0)){
               jT4Serie.setText(Integer.toString(livros.get(0).getSerieDidatica()));
            }
            if(!(livros.get(0).getCdd()==0)){
                String cdd = Integer.toString(livros.get(0).getCdd());
                if(cdd.length()==2){
                    jT5Cdd.setText("0"+(Integer.toString(livros.get(0).getCdd())));
                }else if(cdd.length()==1){
                    jT5Cdd.setText("00"+(Integer.toString(livros.get(0).getCdd())));
                }else{
                    jT5Cdd.setText((Integer.toString(livros.get(0).getCdd())));
                }
            }
            jT6Cdu.setText(livros.get(0).getCdu());
            if(!(livros.get(0).getAnoTombamento()==0)){
            jT7AnoTombamento.setText(Integer.toString(livros.get(0).getAnoTombamento()));
            }
            jT8Quantidade.setText(Integer.toString(livros.get(0).getQuantidade()));
            if(!(livros.get(0).getVolume()==0)){
            jT9Volume.setText(Integer.toString(livros.get(0).getVolume()));
            }
            jT10Editora.setText(livros.get(0).getEditora());
            if(!(livros.get(0).getAnoPublicacao()==0)){
            jT11AnoPublicado.setText(Integer.toString(livros.get(0).getAnoPublicacao()));
            }
            jT12LocalPublicado.setText(livros.get(0).getLocal());
            jT13FormaAq.setText(livros.get(0).getFormaAdquirida());
            jT14Obs.setText(livros.get(0).getObservacao());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar registro.");
        }
       
        // Ao selecionar um registro, os campos são ativados possibilitando fazer alterações
        habilitaCamposAlterar();
    }//GEN-LAST:event_jTablePesquisaMouseClicked
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        // habilita a janela principal
        telaPrincipal.setEnabled(true);
        
    }//GEN-LAST:event_formWindowClosed

    private void jT0RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT0RegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT0RegistroActionPerformed

    private void jT3DisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT3DisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT3DisciplinaActionPerformed

    private void jT1TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT1TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT1TituloActionPerformed

    private void jT2AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT2AutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT2AutorActionPerformed

    private void jT10EditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT10EditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT10EditoraActionPerformed

    private void jT11AnoPublicadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT11AnoPublicadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT11AnoPublicadoActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        limpaCampos();

    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        habilitaCampos();
        // Limpa os dados dos campos
    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrar1ActionPerformed
        cadastraRegistro();

    }//GEN-LAST:event_jBCadastrar1ActionPerformed

    private void jBCadastrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrar2ActionPerformed
        try {
            alteraRegistro();
            BdLivro d = new BdLivro();
            livros = d.getLista("%"+""+"%"); 
            // Após pesquisar os contatos, executa o método p/ exibir o resultado na tabela pesquisa
            mostraPesquisa(livros);
            livros.clear();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao alterar registro.");
        }
    }//GEN-LAST:event_jBCadastrar2ActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        try {
            excluirRegistro();
            BdLivro d = new BdLivro();
            livros = d.getLista("%"+""+"%");
            // Após pesquisar os contatos, executa o método p/ exibir o resultado na tabela pesquisa
            mostraPesquisa(livros);
            livros.clear();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao excluir registro.");
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jT6CduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT6CduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT6CduActionPerformed

    private void jT5CddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT5CddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT5CddActionPerformed
    
    
    
    
    /* ----CADASTRO-> */
    // MÉTODOS:
    
    // Método p/ cadastrar um registro no banco de dados.
    
    private void cadastraRegistro() {
            // Antes de cadastrar, verifica se os campos foram preenchidos
            if (verificaDados()) {
                try {
                    Livro l = new Livro();
                    if("".equals(jT0Registro.getText())){
        
                    }else{
                        l.setRegistro(Integer.valueOf(jT0Registro.getText()));
                    }
                    l.setTitulo(jT1Titulo.getText());
                    l.setAutor(jT2Autor.getText());
                    l.setDisciplina(jT3Disciplina.getText());
                    if(!("".equals(jT4Serie.getText()))){
                        l.setSerieDidatica(Integer.valueOf(jT4Serie.getText()));
                    }
                    if(!("".equals(jT5Cdd.getText()))){
                    l.setCdd(Integer.valueOf(jT5Cdd.getText()));
                    }
                    if(!("".equals(jT6Cdu.getText()))){
                    l.setCdu(jT6Cdu.getText());
                    }
                    if(!("".equals(jT7AnoTombamento.getText()))){
                    l.setAnoTombamento(Integer.valueOf(jT7AnoTombamento.getText()));
                    }
                    l.setQuantidade(Integer.valueOf(jT8Quantidade.getText()));
                    if(!("".equals(jT9Volume.getText()))){
                    l.setVolume(Integer.valueOf(jT9Volume.getText()));
                    }
                    l.setEditora(jT10Editora.getText());
                    if(!("".equals(jT11AnoPublicado.getText()))){
                    l.setAnoPublicacao(Integer.valueOf(jT11AnoPublicado.getText()));
                    }
                    l.setLocal(jT12LocalPublicado.getText());
                    l.setFormaAdquirida(jT13FormaAq.getText());
                    l.setObservacao(jT14Obs.getText());
                    
                    BdLivro d = new BdLivro();

                    d.adicionaLivro(l);

                    JOptionPane.showMessageDialog(rootPane, "Dados cadastrados com sucesso.");
                    desabilitaCampos();

                    livros = d.getLista("%"+""+"%"); 
                    // Após pesquisar os contatos, executa o método p/ exibir o resultado na tabela pesquisa
                    mostraPesquisa(livros);
                    livros.clear();

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar livro.");
                }
            }
    }
    
    // Método p/ validação do formulário
    private boolean verificaDados() {
        if (
            (!jT1Titulo.getText().equals("")) &&
            (!jT2Autor.getText().equals("")) &&
            (!jT8Quantidade.getText().equals("")) &&
            (!jT10Editora.getText().equals("")) &&
            (!jT12LocalPublicado.getText().equals(""))
        ){ 
            
            return true;
            
         }else{
          JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos obrigatórios(*)");
         }
        return false;
    }
    
    // Método p/ concatenar a data
    /*private String data() {
        String d = jT2DataAno.getText() + "-" + jT2DataMes.getText() + "-" + jT2DataDia.getText();
        
        return d;
    }*/
    /* <-CADASTRO---- */ 
    
    
    
    
    /* ----PESQUISA-> */
    // MÉTODOS:   
    
    // Edita os campos e colunas da tabela de resultados
    DefaultTableModel tmLivro = new DefaultTableModel(new Object[] {"Registro", "Título", "Autor(a)", "Editora", "Nº Exemplar"}, 0) {
    @Override
    public boolean isCellEditable(int rowIndex, int mColIndex){  
    return false;  
    }
    };
 
    List<Livro> livros;

   
    // Lista a quantidade de resultado, de acordo com o nome passado no campo pesquisa
    private void listaContatos() throws SQLException {
        limpaCampos();
        BdLivro d = new BdLivro();
        livros = d.getLista("%" + jTPesquisar.getText() + "%"); 
        
        // Após pesquisar os contatos, executa o método p/ exibir o resultado na tabela pesquisa
        mostraPesquisa(livros);
        livros.clear();
    }
    
    // Mostra a lista de resultado de acordo com o nome passado no campo pesquisa
    private void mostraPesquisa(List<Livro> livros) {
        // Limpa a tabela sempre que for solicitado uma nova pesquisa
        limparTabela();
        
        if (livros.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nenhum registro encontrado.");
        } else {            
            // Linha em branco usada no for, para cada registro é criada uma nova linha 
            String[] linha = new String[] {null, null, null, null, null, null, null};
            // P/ cada registro é criada uma nova linha, cada recebe linha os campos do registro
            for (int i = 0; i < livros.size(); i++) {
                tmLivro.addRow(linha);
                tmLivro.setValueAt(livros.get(i).getRegistro(), i, 0);
                tmLivro.setValueAt(livros.get(i).getTitulo(), i, 1);
                tmLivro.setValueAt(livros.get(i).getAutor(), i, 2);
                tmLivro.setValueAt(livros.get(i).getEditora(), i, 3);
                tmLivro.setValueAt(livros.get(i).getQuantidade(), i, 4);
            }            
        }
    }
    
    // Limpa a tabela de resultados
    private void limparTabela() {       
        while (tmLivro.getRowCount() > 0) {            
            tmLivro.removeRow(0);
        }
    } 
    /* <-PESQUISA---- */      
    
    
    
    /* ----EXCLUIR-> */
    // MÉTODOS:
    
    // Exclui resgistro
    private void excluirRegistro() throws SQLException {
        // Se algum registro estiver selecionado
        if (jTablePesquisa.getSelectedRow() != -1) {
            // Exibe uma janela de confirmação antes de exluir o registro
            int resp = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir este registro?",
                    "Confirmação!", JOptionPane.YES_NO_OPTION);

            // Se a confirmação for SIM
            if (resp == JOptionPane.YES_NO_OPTION) {
                // Recebe a linha selecionada
                int linhaSelecionada = jTablePesquisa.getSelectedRow();
                // Recebe o ID da linha selecionada
                int registro = (int) jTablePesquisa.getValueAt(linhaSelecionada, 0);
                // Remove o registro, usando como parâmetro, o id da linha selecionada                
                BdLivro d = new BdLivro();
                d.remove(registro);

                JOptionPane.showMessageDialog(rootPane, "Livro excluido com sucesso.");
                limpaCampos();
                desabilitaCampos();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Livro não selecionado.");
        }
    }
    /* <-EXCLUIR---- */
    
    
    
    
    /* ----ALTERAR-> */
    // MÉTODOS:
    
    // Altera registro
    private void alteraRegistro() throws SQLException {
        if ((jTablePesquisa.getSelectedRow() != -1) && (!jT0Registro.isEditable()) && (verificaDados())) {
            int resp = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente alterar este registro?",
                    "Confirmação!", JOptionPane.YES_NO_OPTION);

            // Se a confirmação for SIM
            if (resp == JOptionPane.YES_NO_OPTION) {                

                Livro l = new Livro();
                BdLivro d = new BdLivro();
                
                l.setRegistro(Integer.valueOf(jT0Registro.getText()));
                l.setTitulo(jT1Titulo.getText());
                l.setAutor(jT2Autor.getText());
                l.setDisciplina(jT3Disciplina.getText());
                if(!("".equals(jT4Serie.getText()))){
                l.setSerieDidatica(Integer.valueOf(jT4Serie.getText()));
                }
                if(!("".equals(jT5Cdd.getText()))){
                l.setCdd(Integer.valueOf(jT5Cdd.getText()));
                }
                l.setCdu(jT6Cdu.getText());
                if(!("".equals(jT7AnoTombamento.getText()))){
                l.setAnoTombamento(Integer.valueOf(jT7AnoTombamento.getText()));
                }
                l.setQuantidade(Integer.valueOf(jT8Quantidade.getText()));
                if(!("".equals(jT9Volume.getText()))){
                l.setVolume(Integer.valueOf(jT9Volume.getText()));
                }
                l.setEditora(jT10Editora.getText());
                if(!("".equals(jT11AnoPublicado.getText()))){
                l.setAnoPublicacao(Integer.valueOf(jT11AnoPublicado.getText()));
                }
                l.setLocal(jT12LocalPublicado.getText());
                l.setFormaAdquirida(jT13FormaAq.getText());
                l.setObservacao(jT14Obs.getText());    

                d.altera(l);
                
                JOptionPane.showMessageDialog(rootPane, "Livro alterado com sucesso.");
                limpaCampos();
                desabilitaCampos();
                listaContatos();
            }
        } else {
                JOptionPane.showMessageDialog(rootPane, "Livro não selecionado.");
        }
    }
    /* <-ALTERAR---- */
    
    
    
    
    /* ----OUTROS-> */
    // MÉTODOS:
    
    // Limpa os campos do formulário
    private void limpaCampos() {
        jT0Registro.setText("");
        jT1Titulo.setText("");
        jT2Autor.setText("");
        jT3Disciplina.setText("");
        jT4Serie.setText("");
        jT5Cdd.setText("");
        jT6Cdu.setText("");
        jT7AnoTombamento.setText("");
        jT8Quantidade.setText("");
        jT9Volume.setText("");
        jT10Editora.setText("");
        jT11AnoPublicado.setText("");
        jT12LocalPublicado.setText("");
        jT13FormaAq.setText("");
        jT14Obs.setText("");
    }
    
    // Desabilita os campos do formulário
    private void desabilitaCampos() {
        jT0Registro.setEditable(false);
    }
    
    // Habilita os campos do formulário
    private void habilitaCampos() {
        jT0Registro.setEditable(true);
    }
    
    private void habilitaCamposAlterar() {
        
        jT0Registro.setEditable(false);

    }
    
    
    /* <-OUTROS---- */
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFLivro().setVisible(true);
            }
        });
    }    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBCadastrar1;
    private javax.swing.JButton jBCadastrar2;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBNovo;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jT0Registro;
    private javax.swing.JTextField jT10Editora;
    private javax.swing.JTextField jT11AnoPublicado;
    private javax.swing.JTextField jT12LocalPublicado;
    private javax.swing.JTextField jT13FormaAq;
    private javax.swing.JTextArea jT14Obs;
    private javax.swing.JTextField jT1Titulo;
    private javax.swing.JTextField jT2Autor;
    private javax.swing.JTextField jT3Disciplina;
    private javax.swing.JTextField jT4Serie;
    private javax.swing.JTextField jT5Cdd;
    private javax.swing.JTextField jT6Cdu;
    private javax.swing.JTextField jT7AnoTombamento;
    private javax.swing.JTextField jT8Quantidade;
    private javax.swing.JTextField jT9Volume;
    private javax.swing.JTextField jTPesquisar;
    private javax.swing.JTable jTablePesquisa;
    // End of variables declaration//GEN-END:variables

}
